### ISSUE TITLE
Website not found anymore?

### ISSUE THREAD

**Issue by Jack-Chronicle** [arn4v/bookmarky#4]
Was gonna check the site recently, but noticed that it wasn't loading. Thought it may just be down, but each time I checked it it still wouldn't load.
was it taken down? is it still available, or is it being shut down completely?

**Comment by ashutoshsaboo** [comment]
+1 @arn4v has this been shutdown?

**Comment by arn4v** [comment]
@Jack-Chronicle @ashutoshsaboo Just pushed an update moving away from graphql to trpc. Will be making it live before 31st. I'm looking to rebrand and moving to another domain, name suggestions are welcome.

**Comment by arn4v** [comment]
It's live on https://bookmarky.mnsht.xyz
